import { palette } from './palette'

export const colors = {
  astrict: palette.paleCarmine,
  background: palette.whiteSmoke,
  blueKiteHeader: palette.bostonBlue,
  blueKiteSecondary: palette.winterWizard,
  blueKiteTertiary: palette.pacificBlue,
  blueKiteRevenueCardBackground: palette.azureishWhite,
  buttonBorder: palette.silver,
  cardBackground: palette.white,
  cardBorderSecondary: palette.chineseWhite,
  comment: palette.persianRed,
  confirmTag: palette.lavenderBlue,
  confirmTagText: palette.cyanCobaltBlue,
  dashBoardCardBackground: palette.lightCyan,
  dash: palette.silver,
  deletedTagText: palette.davyGray,
  deleteTag: palette.argentGray,
  description: palette.arsenic,
  disabledSwitch: palette.granite26,
  dot: palette.greenCyan25,
  filterButtonBg: palette.chagallGreen,
  highlight: palette.shadowGreen,
  inputBorder: palette.platinum,
  lightGreenBackground: palette.americanGreen,
  modalOverlay: 'rgba(0, 0, 0, 0.64)',
  noteBackground: palette.feldspar12,
  notStartTag: palette.paleGoldenrod,
  notStartTagText: palette.lemonCurry,
  onboardingBackground: palette.cultured,
  overlay: palette.blackOverlay,
  palette,
  pendingTag: palette.feldspar,
  pendingTagText: palette.ochre,
  primary: palette.eden,
  primaryText: palette.raisinBlack,
  processingTag: palette.teaGreen,
  rejectedTag: palette.babyPink,
  secondary: palette.greenCyan,
  secondaryText: palette.granite,
  shadow: palette.black,
  switchGradient: palette.white00,
  switchGradient06: palette.white06,
  switchGradient12: palette.white12,
  tabBorder: palette.pomonaGreen10,
  switchBorder06: palette.white06,
  switchBorder12: palette.white12,
  switchBorder: palette.white00,
  transparent: 'transparent',
  whatsAppButton: palette.americanGreen,
}

export const switchBorderGradient = [
  colors.switchBorder12,
  colors.switchBorder06,
  colors.switchBorder,
]
